# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Messaging'

target 'SimpleFcmClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleFcmClient

  target 'SimpleFcmClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
